Repository openshift/external-dns-operator, pull requests merged in 2022-04, with the labels that each got.

#129 e2e: infoblox - use public dns name
  README.md
  test/e2e/infoblox.go
Labels: lgtm, approved

#132 rbac: operand rbac out of the extras, add end user cluster roles
  README.md
  bundle/manifests/external-dns_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/external-dns_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/externaldns-editor_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/externaldns-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
  config/rbac/extra-roles.yaml
  config/rbac/kustomization.yaml
  config/rbac/operand_role.yaml
  config/rbac/operand_rolebinding.yaml
  test/e2e/operator_test.go
Labels: qe-approved, docs-approved, lgtm, approved, px-approved

#133 doc: release-branch mapping
  docs/openshift.md
Labels: qe-approved, docs-approved, lgtm, approved, px-approved

#127 Adds a secret checksum annotation to deployment
  pkg/operator/controller/externaldns/controller.go
  pkg/operator/controller/externaldns/controller_test.go
  pkg/operator/controller/externaldns/deployment.go
  pkg/operator/controller/externaldns/deployment_test.go
  pkg/operator/controller/utils/test/vars.go
Labels: qe-approved, docs-approved, lgtm, approved, tide/merge-method-squash, px-approved

#140 e2e: create ingress controller in openshift-ingress-operator namespace
  test/e2e/operator_test.go
Labels: qe-approved, docs-approved, lgtm, approved, px-approved

#138 use public golang 1.17 for the local builds
  Dockerfile
Labels: qe-approved, docs-approved, lgtm, approved, px-approved

#142 rbac: remove operand cluster permissions
  bundle/manifests/external-dns-operator.clusterserviceversion.yaml
  config/rbac/extra-roles.yaml
  config/rbac/operator_role.yaml
  config/rbac/role.yaml
  pkg/operator/operator.go
Labels: qe-approved, docs-approved, lgtm, approved, px-approved

#143 Dockerfile: fix wrong tag of golang image
  Dockerfile
Labels: qe-approved, docs-approved, lgtm, approved, px-approved
